export const NOTICE_TEMPLATES = {
  REFERRAL_COMMISSION: 'REFERRAL_COMMISSION',
  SHARE_PNL_REWARD: 'SHARE_PNL_REWARD',
  UPGRADE_ACCOUNT_TIER: 'UPGRADE_ACCOUNT_TIER',
  FEED_ORDER_UPDATED: 'FEED_ORDER_UPDATED',
  FEED_ORDER_CLOSED: 'FEED_ORDER_CLOSED',
  FEED_CALLER_RECEIVED_STAR: 'FEED_CALLER_RECEIVED_STAR',
};
