export const NOTIFICATION_QUEUE_NAME = 'notification_queue';

export enum NOTIFICATION_QUEUE_EVENT {
  PROCESS_FOLLOWER_NOTIFICATIONS = 'process_follower_notifications',
  PROCESS_REFERRAL_NOTIFICATIONS = 'process_referral_notifications',
  PROCESS_STAR_DONATION_NOTIFICATIONS = 'process_star_donation_notifications',
  PROCESS_COMMISSION_SHARES = 'process_commission_shares',
  PROCESS_COMMISSION_REFERRALS_NOTIFICATIONS = 'process_commission_referrals_notifications',
}

export const MAX_FOLLOW_AGE_MINUTES = 30;
export const MAX_REFERRAL_AGE_MINUTES = 30;
export const MAX_STAR_DONATE_AGE_MINUTES = 30;
export const MAX_COMMISSION_AGE_MINUTES = 5;
export const MAX_COMMISSION_ORDER_AGE_MINUTES = 5;

export enum NOTIFICATION_NAME {
  NEW_FOLLOWER = 'NEW_FOLLOWER',
  NEW_FOLLOWERS = 'NEW_FOLLOWERS',
  NEW_REFFERAL = 'NEW_REFFERAL',
  NEW_REFFERALS = 'NEW_REFFERALS',
  FUTURES_CALLING = 'FUTURES_CALLING',
  FUTURES_ADD_VOL = 'FUTURES_ADD_VOL',
  NEW_COPIER = 'NEW_COPIER',
  FUTURES_EDIT_TP_SL = 'FUTURES_EDIT_TP_SL',
  FUTURE_OPENED_SEND_TO_COPIER = 'FUTURE_OPENED_SEND_TO_COPIER',
  FUTURE_LIQUIDATE_SEND_TO_COPIER = 'FUTURE_LIQUIDATE_SEND_TO_COPIER',
  FUTURE_HIT_SL_SEND_TO_COPIER = 'FUTURE_HIT_SL_SEND_TO_COPIER',
  FUTURE_HIT_TP_SEND_TO_COPIER = 'FUTURE_HIT_TP_SEND_TO_COPIER',
  FUTURE_CANCEL_SEND_TO_COPIER = 'FUTURE_CANCEL_SEND_TO_COPIER',
  FUTURE_CLOSE_SEND_TO_COPIER = 'FUTURE_CLOSE_SEND_TO_COPIER',
  FOLLOWING_TP = 'FOLLOWING_TP',
  FOLLOWING_PROFIT = 'FOLLOWING_PROFIT',
  TIP_STAR = 'TIP_STAR',
  TIP_STARS = 'TIP_STARS',
  COMMISSION_REF = 'COMMISSION_REF',
  COMMISSION_SHARE = 'COMMISSION_SHARE',
  RANK_CHANGED = 'RANK_CHANGED',
}

export const NOTIFICATION_GROUP = {
  SOCIAL: 'SOCIAL',
  TRADE: 'TRADE',
  SYSTEM: 'SYSTEM',
  GENERAL: 'GENERAL',
  EARN: 'EARN',
};

export enum NotificationStatus {
  NONE = 0,
  EMITTED = 1,
  READ = 2,
  DELETED = 3,
  UNRECOGNIZED = -1,
}

export enum LANGUAGE {
  VI = 'vi',
  EN = 'en',
}

//star ~ ton
export const STAR_USD_PRICE = 0.013;
export const CALLER_RECEIVE_RATE = 0.5;
